[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Thello/linker.ld",
    "-C", "link-arg=-no-pie",
    "-C", "relocation-model=static",
]
